cmake_minimum_required(VERSION 4.2)
project(first_test)

set(CMAKE_CXX_STANDARD 20)

add_executable(first_test main.cpp
        Sum.cpp
        "Short Sort.cpp"
        "String Task.cpp"
        Increasing.cpp
        Homework.cpp
        Koshary.cpp
        "Sereja and Dima.cpp"
        Twins.cpp
        "Greatest Common Factor.cpp"
        FrequancyArray.cpp
        TargetSum.cpp
        PrefixArray.cpp
        BiggerLetter.cpp
        "Brr Brrr Patapim.cpp"
        Dragons.cpp
        Add.cpp
)
